### ISSUE TITLE
Proposed changes to "Clock Correction"

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#29]
The current specification for clock corrections is:

## Full structure (as YAML):

```yaml
"clock_correction":
    "drift":
        "base": {"instrument": "Seascan MCXO, ~1e-8 nominal drift", "reference": "GNSS"}
        "type": "piecewise"
        "interpolation": "linear"
        "syncs_reference_instrument": 
            - ["2015-04-23T11:20:00", "2015-04-23T11:20:00"]
            - ["2016-05-27T14:00:00.2450", "2016-05-27T14:00:00"]
```
 
## As a StationXML Comment
```xml
<Comment subject="clock_correction">
    <Value>{"drift": {"base": {"instrument": "Seascan MCXO, ~1e-8 nominal drift", "reference": "GNSS"}, "type": "piecewise", "interpolation": "linear", "syncs_reference_instrument": [["2015-04-23T11:20:00", "2015-04-23T11:20:00"], ["2016-05-27T14:00:00.2450", "2016-05-27T14:00:00"]]}}</Value>
 </Comment>
```

## In msmod drift correction specification file
```
interpolation: linear
# Reference time           Instrument time
2015-04-23T11:20:00        2015-04-23T11:20:00
2016-05-27T14:00:00.2450   2016-05-27T14:00:00"
```

 
Propose 2 changes:

1. [ ] combine `type` and `interpolation` into `type`: ['piecewise_linear', 'cubic_spline']
2. [ ] Allow instrument times to be specified as seconds to add to reference time

The new msmod specification would look like

## In msmod drift correction specification file
```
type: piecewise_linear
# Reference time         Instrument time
2015-04-23T11:20:00        +0.0
2016-05-27T14:00:00.2450   2016-05-27T14:00:00"
```
